Repository jcsnorlax97/rentr, pull requests merged in 2021-02, with the labels that each got.

#41 Origin/develop/faq user stories #38
  Documentation/Project Proposal.txt
Labels: documentation

#43 Issue #42: Add Feb 3rd meeting minute into Minutes.md
  meetingMinutes/Minutes.md
Labels: documentation

#45 Issue #44: Add project summary & core features into README.md
  Documentation/CORE_FEATURES.md
  README.md
Labels: documentation

#47 Update README.md and CORE_FEATURES.md
  Documentation/CORE_FEATURES.md
  README.md
Labels: documentation

#59 Issue #03 - Backend Server Setup (Node.Js, Express.Js, PostgresDB)
  server/.env.template
  server/.eslintrc.json
  server/.gitignore
  server/.vscode/settings.json
  server/README.md
  server/api/index.js
  server/api/routes/api.js
  server/api/routes/user.js
  server/app.js
  server/config/config.js
  server/controllers/api.js
  server/controllers/user.js
  server/dao/user.js
  server/dao/user.test.js
  server/db/db.js
  server/di-setup.js
  server/dto/user.js
  server/error/api-error-handler.js
  server/error/api-error.js
  server/middleware/validate.js
  server/migrations/dropUserTable.sql
  server/migrations/init.sql
  server/package-lock.json
  server/package.json
  server/services/user.js
Labels: High Priority, backend

#58 initial design of login and register
  frontend/.eslintcache
  frontend/src/App.js
  frontend/src/actions/Home.js
  frontend/src/pages/Home.jsx
  frontend/src/pages/HomePage.jsx
  frontend/src/reducers/Home.js
  frontend/src/reducers/index.js
  frontend/src/styles/Home.css
  frontend/src/styles/HomePage.css
Labels: High Priority, frontend

#68 Issue #60: Fix ping API endpoint typo
  server/controllers/api.js
Labels: backend, bug, database

#69 Issue #61: Fix Bug via changing DB naming conventions
  server/dao/user.js
  server/migrations/init.sql
Labels: backend, bug, database

#72 Issue #71: Implement GET Route for retrieving single user.
  server/README.md
  server/api/routes/user.js
  server/controllers/user.js
  server/dao/user.js
  server/services/user.js
Labels: backend, database, dev-task

#73 Issue #67: Implement POST route for adding new listing & Write unit test for it.
  server/README.md
  server/api/index.js
  server/api/routes/listing.js
  server/controllers/listing.js
  server/dao/listing.js
  server/di-setup.js
  server/dto/listing.js
  server/migrations/dropUserTable.sql
  server/migrations/init.sql
  server/services/listing.js
  server/services/listing.test.js
Labels: backend, database, dev-task

#70 Issue #51: Writing Unit Test on Account Creation POST request
  server/package.json
  server/services/user.test.js
Labels: backend, database, dev-task

#74 Issue62 task get route for all existing listings
  server/api/routes/listing.js
  server/controllers/listing.js
  server/dao/listing.js
  server/services/listing.js
  server/services/listing.test.js
Labels: backend, database, dev-task

#75 Post route for User Login closes #52
  server/api/routes/user.js
  server/controllers/user.js
  server/dao/user.js
  server/migrations/init.sql
  server/package-lock.json
  server/package.json
  server/services/user.js
Labels: High Priority, backend

#80 Issue#79 jwt validation after login closes #79
  server/api/routes/listing.js
  server/error/api-error.js
  server/middleware/validate.js
  server/middleware/validateLoggedIn.js
Labels: High Priority, backend, dev-task

#77 implemented user story that allows user to see the listings && pagination included for listings issue63
  frontend/.gitignore
  frontend/Browersetting/ReadMe.md
  frontend/Browersetting/noCors.txt
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/actions/Home.js
  frontend/src/actions/HomePage.js
  frontend/src/actions/ListingDetail.js
  frontend/src/components/HomeContent/homeContent.jsx
  frontend/src/components/Listing/listing.jsx
  frontend/src/data/urls.js
  frontend/src/index.js
  frontend/src/pages/HomePage.jsx
  frontend/src/pages/Listing.jsx
  frontend/src/reducers/Home.js
  frontend/src/reducers/HomePage.js
  frontend/src/reducers/ListingDetail.js
  frontend/src/reducers/index.js
  frontend/src/styles/HomePage.css
  frontend/src/styles/Listing.css
Labels: frontend

#82 Issue64 task get route for single listing
  server/api/routes/listing.js
  server/controllers/listing.js
  server/dao/listing.js
  server/services/listing.js
  server/services/listing.test.js
Labels: backend, database, dev-task

#85 Creating Listing Dialog Basic Form
  .gitignore
  frontend/src/actions/CreateListing.js
  frontend/src/components/CreateListing/CreateListingButton.jsx
  frontend/src/pages/HomePage.jsx
  frontend/src/reducers/CreateListing.js
  frontend/src/reducers/index.js
  frontend/src/styles/CreateListing.css
Labels: frontend

#86 Issue #78: Update config & db for backend server deployment into Heroku for front-end testing
  server/config/config.js
  server/db/db.js
  server/package.json
Labels: backend, database, dev-task

#89 Issue #88: Fix user registration bugs in deployed environments
  server/app.js
  server/dto/user.js
  server/error/api-error-handler.js
  server/migrations/init.sql
Labels: High Priority, backend, bug, database

#91 Issue #90: Initial Travis-CI Setup
  .travis.yml
  frontend/src/App.test.js
  server/dao/user.test.js
Labels: High Priority, dev-task

#93 Issue #81: Do Final Code Clean Up & Update Listing DB Scheme
  server/.env.template
  server/api/routes/listing.js
  server/api/routes/user.js
  server/controllers/listing.js
  server/controllers/user.js
  server/dao/listing.js
  server/dao/user.js
  server/dto/listing.js
  server/error/api-error.js
  server/middleware/validateLoggedIn.js
  server/migrations/init.sql
  server/services/listing.js
  server/services/listing.test.js
  server/services/user.js
  server/services/user.test.js
Labels: backend, database, dev-task

#95 fixed create listing button style issue, added drop photo zone when create listing, field validation
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/actions/CreateListing.js
  frontend/src/components/CreateListing/CreateListingButton.jsx
  frontend/src/components/ImageUpload/ImageUploader.jsx
  frontend/src/pages/Apartment.jsx
  frontend/src/pages/HomePage.jsx
  frontend/src/pages/Profile.jsx
  frontend/src/reducers/CreateListing.js
  frontend/src/styles/CreateListing.css
  frontend/src/styles/ImageUploader.css
Labels: dev-task, frontend

#98 Issue #97: Fix Login Bug when invalid combination between email and password are entered.
  server/controllers/user.js
Labels: backend, bug

#101 Issue #100: Update unit testing for the listing class
  server/README.md
  server/services/listing.test.js
Labels: backend, database, dev-task, justin-personal-label-for-marking-new-issues, testing

#99 Issue #97: Integrate rest services for login, post listing, and fetch listings
  frontend/src/actions/HomePage.js
  frontend/src/components/CreateListing/CreateListingButton.jsx
  frontend/src/components/ImageUpload/ImageUploader.jsx
  frontend/src/components/Listing/listing.jsx
  frontend/src/data/urls.js
  frontend/src/pages/HomePage.jsx
  frontend/src/reducers/HomePage.js
  frontend/src/styles/CreateListing.css
  frontend/src/styles/HomePage.css
  frontend/src/styles/Listing.css
Labels: High Priority, dev-task, frontend, justin-personal-label-for-marking-new-issues

#103 Added diagrams
  designAndArchitecture/AddApartmentListings.png
  designAndArchitecture/AddApatmentDetails.png
  designAndArchitecture/AddapartmentPhotos.png
  designAndArchitecture/LogIn.png
  designAndArchitecture/SignUp.png
  designAndArchitecture/classDiagram_rentr.jpeg
  designAndArchitecture/readme.md
  designAndArchitecture/rentr_sprint2_block_diagram_v3.jpg
Labels: documentation

#104 Update Minutes Documentation
  meetingMinutes/Minutes.md
Labels: documentation

#106 Issue #105: Fix "PayloadTooLarge" Bug by adding config parameters to express.json() & express.urlencoded()
  server/app.js
Labels: High Priority, backend, bug

#107 Issue #102: Update readme in both /server & root-level
  server/README.md
Labels: documentation

#109 Removed the unecessary code
  frontend/src/actions/CreateListing.js
  frontend/src/components/CreateListing/CreateListingButton.jsx
  frontend/src/components/ImageUpload/ImageUploader.jsx
  frontend/src/reducers/CreateListing.js
Labels: frontend

#110 Issue #102: Creates the initial Test Plan in .docx format
  Documentation/Test_Plan.docx
Labels: documentation

#111 Issue #102: Update root-level README.md
  README.md
Labels: documentation

#112 Issue #102: Initial Test Plan
  Documentation/Test_Plan.docx
  Documentation/Test_Plan.pdf
Labels: documentation
