Repository jcsnorlax97/rentr, pull requests merged in 2021-03, with the labels that each got.

#114 Update meeting minute for Week 6
  meetingMinutes/Minutes.md
Labels: documentation

#135 Update core features
  Documentation/CORE_FEATURES.md
Labels: Epic, documentation

#144 Componentize/refactor login dialog
  frontend/src/actions/HomePage.js
  frontend/src/actions/LoginDialogButton.js
  frontend/src/components/LoginDialogButton.jsx
  frontend/src/pages/HomePage.jsx
  frontend/src/reducers/LoginButtonDialog.js
  package-lock.json
Labels: dev-task, frontend

#147 Add listing main view container
  frontend/src/components/Listing/listing.jsx
  frontend/src/pages/HomePage.jsx
  frontend/src/styles/Listing.css
Labels: frontend

#150 Issue #149: Get listings for a specific user
  server/api/routes/user.js
  server/controllers/user.js
  server/dao/listing.js
  server/dto/listing.js
  server/migrations/init.sql
  server/services/listing.js
Labels: backend, database, dev-task

#145 Issue #140: Filter listing via ranges
  server/api/routes/listing.js
  server/controllers/listing.js
  server/dao/listing.js
  server/dto/listing.js
  server/dto/listingReqQueryString.js
  server/middleware/validateReqQueryString.js
  server/middleware/validateReqQueryString.test.js
  server/migrations/init.sql
  server/services/listing.js
  server/utils/expressMocker.js
Labels: backend, database, dev-task

#151 Issue #141: Filter listing via boolean values
  server/dao/listing.js
  server/dto/listingReqQueryString.js
  server/middleware/validateReqQueryString.test.js
Labels: High Priority, backend, database, dev-task

#152 Issue #142: Filter listing via keywords
  server/dao/listing.js
  server/dto/listingReqQueryString.js
  server/middleware/validateReqQueryString.test.js
Labels: High Priority, backend, database, dev-task

#143 Issue #132: Implement put route to update listing
  server/api/routes/user.js
  server/controllers/user.js
  server/dao/listing.js
  server/services/listing.js
  server/services/listing.test.js
Labels: backend, database, dev-task

#155 Implementation of search feature
  frontend/src/actions/AdvancedSeach.js
  frontend/src/actions/HomePage.js
  frontend/src/actions/ListingDetail.js
  frontend/src/components/AdvancedSearch.jsx
  frontend/src/components/CreateListing/CreateListingButton.jsx
  frontend/src/components/Listing/listing.jsx
  frontend/src/components/LoginDialogButton.jsx
  frontend/src/data/dropdownData.js
  frontend/src/index.js
  frontend/src/pages/HomePage.jsx
  frontend/src/reducers/AdvancedSearch.js
  frontend/src/reducers/HomePage.js
  frontend/src/reducers/ListingDetail.js
  frontend/src/reducers/index.js
  frontend/src/styles/AdvancedSearch.css
  frontend/src/styles/HomeContent.css
  frontend/src/styles/HomePage.css
  frontend/src/styles/Listing.css
Labels: Epic, feature, frontend

#154 Issue #134: Delete route setup
  server/api/routes/user.js
  server/controllers/user.js
  server/dao/listing.js
  server/services/listing.js
  server/services/listing.test.js
Labels: High Priority, backend, database, dev-task

#158 Issue #136: Update SQL script for chain & comment tables
  server/migrations/init.sql
Labels: High Priority, backend, database, dev-task

#159 Integrated rest request for get all listings of a user, also warning messages
  frontend/src/components/CreateListing/CreateListingButton.jsx
  frontend/src/components/Listing/listing.jsx
  frontend/src/components/Profile/Profile.jsx
  frontend/src/styles/Listing.css
Labels: dev-task, frontend

#160 Issue #137: Implement POST request for creating chains & comments
  server/README.md
  server/api/routes/listing.js
  server/controllers/chain.js
  server/controllers/comment.js
  server/dao/chain.js
  server/dao/comment.js
  server/di-setup.js
  server/dto/comment.js
  server/migrations/init.sql
  server/services/chain.js
  server/services/chain.test.js
  server/services/comment.js
  server/services/comment.test.js
Labels: High Priority, backend, database, dev-task

#162 Updated styles for edit panel and more
  frontend/src/components/Listing/listing.jsx
  frontend/src/components/ListingViewer/ListingViewer.jsx
  frontend/src/pages/HomePage.jsx
  frontend/src/reducers/ListingDetail.js
  frontend/src/styles/HomePage.css
  frontend/src/styles/Listing.css
  frontend/src/styles/ListingView.css
Labels: frontend

#163 Issue #138: Implement GET listing comments route
  server/api/routes/listing.js
  server/controllers/listing.js
  server/dao/comment.js
  server/services/comment.js
Labels: High Priority, backend, database, dev-task

#164 Issue #137: Standardize codes by putting createComment & createChain into listingController
  server/api/routes/listing.js
  server/controllers/chain.js
  server/controllers/comment.js
  server/controllers/listing.js
  server/di-setup.js
Labels: High Priority, backend, dev-task

#168 Update QnA stylesheet
  frontend/src/components/ListingViewer/ListingViewer.jsx
  frontend/src/styles/ListingView.css
Labels: dev-task

#167 Added QnA feature
  frontend/src/actions/ListingDetail.js
  frontend/src/components/ListingViewer/ListingViewer.jsx
  frontend/src/reducers/ListingDetail.js
  frontend/src/styles/ListingView.css
Labels: Epic, dev-task, feature, frontend

#170 Fix landlord reply check
  frontend/src/components/ListingViewer/ListingViewer.jsx
Labels: frontend

#169 Update the meeting minutes
  meetingMinutes/Minutes.md
Labels: documentation

#166 Issue #134 #132 Bug #156 #157: Modifications & Bug fixing on deleteListing and updateListing
  server/README.md
  server/api/routes/listing.js
  server/api/routes/user.js
  server/controllers/listing.js
  server/controllers/user.js
  server/dao/listing.js
  server/dto/listing.js
  server/error/api-error.js
  server/migrations/init.sql
  server/services/listing.js
Labels: High Priority, backend, bug, database, dev-task

#175 update feature with new api route
  frontend/src/components/ListingViewer/ListingViewer.jsx
  frontend/src/components/Profile/Profile.jsx
Labels: frontend

#171 Cypress Acceptance Testing
  .gitignore
  server/cypress.json
  server/cypress/fixtures/example.json
  server/cypress/integration/Listing_spec.js
  server/cypress/integration/Search_spec.js
  server/cypress/integration/User_account_spec.js
Labels: testing
