Repository jcsnorlax97/rentr, pull requests merged in 2021-04, with the labels that each got.

#179 QnA bug fix
  frontend/package-lock.json
  frontend/package.json
  frontend/src/actions/ListingDetail.js
  frontend/src/components/ListingViewer/ListingViewer.jsx
  frontend/src/reducers/ListingDetail.js
Labels: bug, dev-task, frontend

#180 POST,GET&PUT request works with `is_available` functionality
  server/dao/listing.js
  server/dto/listing.js
  server/migrations/init.sql
Labels: backend, database, dev-task

#182 Notification for update listing and QnA
  frontend/src/Util/DisplayWarning.jsx
  frontend/src/components/ListingViewer/ListingViewer.jsx
  frontend/src/components/ListingViewer/QnA.jsx
Labels: dev-task, frontend

#186 Image upload bug fix
  frontend/src/actions/ListingDetail.js
  frontend/src/components/CreateListing/CreateListingButton.jsx
  frontend/src/components/ImageUpload/ImageUploader.jsx
  frontend/src/components/Listing/listing.jsx
  frontend/src/components/ListingViewer/ListingViewer.jsx
  frontend/src/components/LoginDialogButton.jsx
  frontend/src/components/Profile/Profile.jsx
  frontend/src/data/dropdownData.js
  frontend/src/reducers/HomePage.js
  frontend/src/reducers/ListingDetail.js
  frontend/src/styles/ListingView.css
Labels: dev-task

#185 issue#34-`Search by City` functionality added as the advanced search
  server/dao/listing.js
  server/dto/listing.js
  server/dto/listingReqQueryString.js
  server/migrations/init.sql
Labels: backend, database, dev-task

#187 Issue 43 mike listing cities
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/AdvancedSearch.jsx
  frontend/src/components/CreateListing/CreateListingButton.jsx
  frontend/src/components/Listing/listing.jsx
  frontend/src/components/ListingViewer/ListingViewer.jsx
  frontend/src/components/ListingViewer/QnA.jsx
  frontend/src/components/Profile/Profile.jsx
  frontend/src/data/dropdownData.js
  frontend/src/pages/HomePage.jsx
  frontend/src/reducers/HomePage.js
  frontend/src/styles/AdvancedSearch.css
  frontend/src/styles/Listing.css
  frontend/src/styles/Profile.css
Labels: dev-task, frontend

#190 Issue 189 disable search spaces
  frontend/src/pages/HomePage.jsx
Labels: bug, frontend

#198 updated meeting minutes
  meetingMinutes/Minutes.md
Labels: documentation

#201 Issue #191-195 (All Acceptance Test): Fix bugs in Acceptance test & Update demo db migration
  server/e2e_tests/advancedSearchTest.js
  server/e2e_tests/creationTest.js
  server/e2e_tests/qnaTests.js
  server/e2e_tests/test01_Registration.js
  server/e2e_tests/test02_Login.js
  server/e2e_tests/test03_ListingCreation.js
  server/e2e_tests/test04_ListingModifications.js
  server/e2e_tests/test05_Search.js
  server/e2e_tests/test06_AdvancedSearch.js
  server/e2e_tests/test06_QuestionCreation.js
  server/e2e_tests/test07_QuestionReply.js
  server/migrations/init-demo.sql
Labels: High Priority, testing

#203 Add comment
  frontend/src/components/CreateListing/CreateListingButton.jsx
  frontend/src/components/ImageUpload/ImageUploader.jsx
Labels: documentation

#204 [MASTER] Final Front-End Code Clean Up
  frontend/src/components/CreateListing/CreateListingButton.jsx
  frontend/src/components/ImageUpload/ImageUploader.jsx
Labels: Low Priority, frontend
